[package]
name = "hecs-query-tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hecs = "0.7"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "tracked_vs_untracked"
harness = false
